/// Flutter icons MyFlutterIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterIcon
///      fonts:
///       - asset: fonts/MyFlutterIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterIcon {
  MyFlutterIcon._();

  static const _kFontFam = 'MyFlutterIcon';
  static const String? _kFontPkg = null;

  static const IconData like = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_chat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waranty = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refund = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData details = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData previous_rounded = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_filled = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_add = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData previous = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_down = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tab = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_outlined = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_outlined = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_outlined = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_outlined = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_call = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bath_tub = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beds = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_bill = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_overview = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
